### ISSUE TITLE
failed filling form

### ISSUE THREAD

**Issue by 1Tado1** [xieqifei/AutoLernraum#6]
random_test has been throwing me this exception since a few days

Traceback (most recent call last):
  File "C:\Users\User\Desktop\Lernraum\Neu\Bib\myclass\lernraum.py", line 451, in __fill_form
    driver.execute_script(fill_form_script)
  File "C:\Users\User\Desktop\Lernraum\Neu\Bib\selenium\webdriver\remote\webdriver.py", line 634, in execute_script
    return self.execute(command, {
  File "C:\Users\User\Desktop\Lernraum\Neu\Bib\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\User\Desktop\Lernraum\Neu\Bib\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: javascript error: Cannot set properties of undefined (setting 'value')
  (Session info: headless chrome=97.0.4692.71)

2022-01-18 09:18:14: filling form failed
2022-01-18 09:18:15: refresh page

**Comment by xieqifei** [comment]
I`m fixing it and pushed a new version.It is not tested and I dont know if it works.  You can read Readme to learn about it.
